[project]
name = "sms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
     "bcrypt>=4.3.0",
    "pandas>=2.3.2",
    "pydantic>=2.11.7",
    "sqlalchemy>=2.0.43",
    "streamlit>=1.48.1",
]
